[package]
name = "day_2_day_1"
version = "0.1.0"
authors = ["Joshua Little <jlittle2001@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
